import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { Proviers } from './GlobalRedux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'kurly',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href={'/'}><li>Home</li></Link>
          <Link href={'/productsList'}><li>Products List</li></Link>
          <Link href={'/cart'}><li>Cart</li></Link>
        </nav>
        <Proviers>
          {children}
        </Proviers>
      </body>
    </html>
  )
}
