import './globals.css'
import Link from "next/link";
import { cookies } from 'next/headers'
import ModeBtn from './ModeBtn';

export const metadata = {
  title: 'Forum',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  let a = cookies().get('mode')
  // console.log(a.value)
  return (
    <html>
      <body className={
        a.value != undefined && a.value == 'dark' ? 'dark' : null
      }>
        <div className="navbar">
          <Link href={'/'}>Home</Link>
          <Link href={'/write'}>Write</Link>
          <Link href={'/list'}>List</Link>
          <ModeBtn mode={a.value == 'dark' ? '🌙' : '🌞'}/>
        </div>
        {children}
      </body>
    </html>
  )
}
