import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="link">Home</Link>
          <Link href="/list" className="link">List</Link>
          <Link href="/cart" className="link">Cart</Link>
        </div>
        {children}  {/* page.js가 들어있음 */}
      </body>
    </html>
  )
}
