import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Forum',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href={'/'}>Home</Link>
          <Link href={'/write'}>Write</Link>
          <Link href={'/list'}>List</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
